version: '2'
services:
  projetoparateste-app:
    image: projetoparateste
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mariadb://projetoparateste-mariadb:3306/projetoparateste
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    ports:
      - 8080:8080
  projetoparateste-mariadb:
    extends:
      file: mariadb.yml
      service: projetoparateste-mariadb
